# Generated by Django 6.1.1 on 2026-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='toyear',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
